# Generated by Django 4.0.3 on 2022-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=256)),
                ('day1', models.CharField(max_length=10)),
                ('dpr1', models.CharField(max_length=256)),
                ('day2', models.CharField(max_length=10)),
                ('dpr2', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
