# Generated by Django 4.0.3 on 2022-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_alter_foodmodel_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
