# Generated by Django 4.0.3 on 2022-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0004_alter_foodmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='step',
            field=models.TextField(),
        ),
    ]
